### ISSUE TITLE
Key Command Request - NOT AN ISSUE

### ISSUE THREAD

**Issue by Coolie1101** [JeffLIrion/python-androidtv#185]
Hi, any chance you can add an "ESC" key command?, my android tv box only exits running apps via the return key on the traditional remote, or esc key on a keyboard.

Thanks
![image](https://user-images.githubusercontent.com/28989417/87889566-3cf94000-ca00-11ea-87b4-5b9597f8c4e0.png)
![image](https://user-images.githubusercontent.com/28989417/87889624-82b60880-ca00-11ea-9a6a-2b51361a2e8b.png)

**Comment by JeffLIrion** [comment]
It looks like its keycode is 111. 

https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_ESCAPE

Can you submit a pull request that adds that constant.

**Comment by Coolie1101** [comment]
@JeffLIrion, thanks for the quick response, sorry, I'm not sure how to submit a pull request.

**Comment by JeffLIrion** [comment]
I took care of it.  

You won't be able to use it until a new release is published.  But you can just use the ADB command `input keyevent 111`.

**Comment by Coolie1101** [comment]
Awesome!, thank you.

**Comment by Coolie1101** [comment]
Do I need to list the commands as below?

```
    action:
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_android_tv
          command: input keyevent 111
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_android_tv
          command: RIGHT
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_android_tv
          command: ENTER
```
