### ISSUE TITLE
state_detection_rules doesn't seems to work

### ISSUE THREAD

**Issue by unstable09** [JeffLIrion/python-androidtv#257]
Hi, I see a problem with state_detection_rules... I wanted to add support for player (one of Polish services with VOD). I figrued out that it changes wake lock size depending on state of the media, while media_session_state is none and audio_state is paused. I prepared this code for my configuration.yaml:
```
media_player:
  - platform: androidtv
    name: AndroidTV_Philips
    host: 192.168.0.11
    device_class: androidtv
    scan_interval: 1
    apps: {}
    state_detection_rules:
      'pl.tvn.player.pl':
        - 'playing':
            'audio_state': paused
            'wake_lock_size': 3
        - 'paused':
            'audio_state': paused
            'wake_lock_size': 2 
        - 'idle'
```
This code not working, I don't know if there is some information how to exlude one of the parameters, because in my case media_session_state is always none...

**Comment by unstable09** [comment]
Ok, that means that my configuration is excaly how I wanted it to be. Problem is that the state is always "paused". For better understanding today I added the configuration to 2 other VODs  (not supported originally) and it works fine. By coincidence this new services has the same logic behind "playing" state as this mentioned above, so logic seems to be ok. 
I also added name for all 3 services. For this `pl.tvn.player.pl` name was not added, for the other 2 it worked.

Maybe is there a bug becasue of the app id (I mean word "player" or 3 dots in id)? I'm trying to look in the code but my skills are not enough for this task...

My current config section with android tv:

```
- platform: androidtv
    name: AndroidTV_Philips
    host: 192.168.0.11
    device_class: androidtv
    scan_interval: 1
    screencap: false
    apps: 
      'pl.tvn.player.pl': "player"
      'pl.festival.atv': "WOW"
      'pl.videostar': "WP Pilot"
    state_detection_rules:
      'pl.tvn.player.pl':
        - 'playing':
            'audio_state': paused
            'wake_lock_size': 3
        - 'paused':
            'audio_state': paused
            'wake_lock_size': 2 
        - 'idle'
      'pl.festival.atv':
        - 'playing':
            'audio_state': paused
            'wake_lock_size': 3
        - 'paused':
            'audio_state': paused
            'wake_lock_size': 2 
        - 'idle'
      'pl.videostar':
        - 'playing':
            'audio_state': paused
            'wake_lock_size': 3
        - 'paused':
            'audio_state': paused
            'wake_lock_size': 2 
        - 'idle'
```
